### ISSUE TITLE
Can domain name be supported for divide?

### ISSUE THREAD

**Issue by stelin** [apache/incubator-shenyu#1600]
## Question

// your question here;

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Divide support domain + port?

![image](https://user-images.githubusercontent.com/1677543/121492781-bf6c6300-ca09-11eb-8d01-eca76feed94a.png)

**Comment by zhaiweij** [comment]
hi. Why does the domain name still need to show the port


On 06/10/2021 ***@***.***> wrote：

Question

// your question here;

Please pay attention on issues you submitted, because we maybe need more details.
If no response anymore and we cannot reproduce it on current information, we will close it.

Divide support domain + port?

**Comment by ttttangzhen** [comment]
If you use local host mapping, you can use it like you said

**Comment by zhaiweij** [comment]
Yes, this is the job of DNS


On 06/10/2021 ***@***.***> wrote：

If you use local host mapping, you can use it like you said

**Comment by stelin** [comment]
![image](https://user-images.githubusercontent.com/1677543/121500383-cfd40c00-ca10-11eb-8258-781cf2baf180.png)
Here can not configure domain. I user to private dns Or k8s dns

**Comment by yu199195** [comment]
Of course you can configure the domain name.  like : www.baidu.com

**Comment by stelin** [comment]
![image](https://user-images.githubusercontent.com/1677543/121501311-b1224500-ca11-11eb-97de-22b7b88ef008.png)

I configured like www.baidu.com, but refresh browser，the configured value is empty! 

![image](https://user-images.githubusercontent.com/1677543/121501745-15dd9f80-ca12-11eb-8357-c72218a595ca.png)

**Comment by stelin** [comment]
I clone code from master.

**Comment by yu199195** [comment]
can checked by youself ?

or config `shenyu.register.props.checked = false`   in shenyu-admin /application.yaml

```
shenyu:
  register:
    registerType: http #http #zookeeper #etcd #nacos #consul
    serverLists: #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      sessionTimeout: 5000
      connectionTimeout: 2000
      checked: false
```
