### ISSUE TITLE
feature common : support external cros filter config.

### ISSUE THREAD

**Issue by qicz** [apache/incubator-shenyu#2001]
using `shenyu.cros-filter-config.*` config the cors filter:
```yml
shenyu:
  cros-filter-config:
    allowed-headers: qicz, custom
    allowed-expose: *
    allowed-methods: *
    allowed-origin: *
    max-age: 18000
```

the `allowed-headers` default is `x-requested-with, authorization, Content-Type, Authorization, credential, X-XSRF-TOKEN, token, username, client`.

 the external config will append to the `allowed-headers`.  the example of `allowed-headers` = `x-requested-with, authorization, Content-Type, Authorization, credential, X-XSRF-TOKEN, token, username, client,  qicz, custom`.
