### ISSUE TITLE
Global Proxy (isFull = true)

### ISSUE THREAD

**Issue by SessionBest** [apache/incubator-shenyu#2682]
### Question

shenyu version: 2.4.1
spring cloud sample
yaml:
```
shenyu:
  client:
    registerType: nacos #zookeeper #etcd #nacos #consul
    serverLists: 10.80.84.160:8848 #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      contextPath: /springcloud
      port: 8884
      nacosNameSpace: "service"
      username: nacos
      password: test
      isFull: true
```
Nacos:
![image](https://user-images.githubusercontent.com/22487139/147808968-9c0aa34b-8455-43f6-bdbe-e7e8c6db646c.png)

shenyu admin:
![image](https://user-images.githubusercontent.com/22487139/147808893-7d987190-cd2a-4abd-b232-11b493070fef.png)

test request:
`http://localhost:9195/springcloud/order/findById?id=100 `

test Response:
```
{
  "code": -107,
  "message": "divide:Can not find selector, please check your configuration!",
  "data": null
}
```

How do I need to set it up and proxy the entire service ?
