### ISSUE TITLE
[BUG] <The handel field in the selecot table became null>

### ISSUE THREAD

**Issue by misaya295** [apache/incubator-shenyu#3027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In one case, divide is configured in the admin, and then the handle field of the selector table in the library has information at first, but the handle becomes null after a few days, and the admin page does not display the information.

![image](https://user-images.githubusercontent.com/45778734/157799604-79bcc104-b3f6-4c5c-9a58-bf48679eb2bf.png)

### Expected Behavior

Configuration information is always persistent in the database, rather than being modified to null

### Steps To Reproduce

1. Configuration information is persisted to mysql
2. a few day later
3. The handel field in the configuration information selector table became null

### Environment

```markdown
ShenYu version(s):docker apache/shenyu-bootstrap:latest docker apache/shenyu-admin:latest
both run on kubernetes
```

**Comment by yu199195** [comment]
pls config this ,if you not want checked real service

```
shenyu:
  register:
    props:
      checked: true
```

**Comment by misaya295** [comment]
@yu199195 
I didn't set this configuration in the first place, do I need to set this configuration now to solve this proble?
```yaml
server:
    port: 9195
    address: 0.0.0.0
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: shenyu-bootstrap
management:
    health:
        defaults:
        enabled: false
shenyu:
    local:
        enabled: true
    file:
        enabled: true
    cross:
        enabled: true
    dubbo:
        parameter: multi
    sync:
        websocket:
          # 根据实际情况填写正确的socket地址
          urls: ws://shenyu-admin-svc.pro.svc.cluster.local:9095/websocket
    exclude:
        enabled: false
        paths:
        - /favicon.ico
    extPlugin:
        enabled: true
        threads: 1
        scheduleTime: 300
        scheduleDelay: 30
    scheduler:
        enabled: false
        type: fixed
        threads: 16
logging:
    level:
        root: info
        org.springframework.boot: info
        org.apache.ibatis: info
        org.apache.shenyu.bonuspoint: info
        org.apache.shenyu.lottery: info
        org.apache.shenyu: info

```

**Comment by yu199195** [comment]
hi， in shenyu admin yaml config

**Comment by misaya295** [comment]
@yu199195 Sorry, my admin configuration only has mysql configuration, should I add this configuration right?

before fixing
```
shenyu:
  database:
    dialect: mysql
    init_script: "sql-script/mysql/schema.sql"
    init_enable: false
spring:
  datasource:
    url: jdbc:mysql://XXXX:3306/shenyu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: XX
    password: XXX
```


after modification
```yaml
shenyu:
  database:
    dialect: mysql
    init_script: "sql-script/mysql/schema.sql"
    init_enable: false
  register:
    props:
      checked: true
spring:
  datasource:
    url: jdbc:mysql://XXXX:3306/shenyu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: XX
    password: XXX
```

**Comment by yu199195** [comment]
```
shenyu:
  register:
    props:
      checked: false
```
