### ISSUE TITLE
how to ignore /favicon.ico request?

### ISSUE THREAD

**Issue by ljwhx2002** [apache/incubator-shenyu#3261]
### Question

when I call my api via browser, this message display:

2022-04-18 09:00:43 [boundedElastic-2] ERROR org.apache.shenyu.plugin.api.utils.WebFluxResultUtils - can not match selector data: divide , /favicon.ico

**Comment by yu199195** [comment]
pls modify this in shenyu-boostrap yaml:

```
shenyu
    exclude:
       enabled: true
       paths:
         - /favicon.ico
```
