### ISSUE TITLE
[BUG] why contextpath "/springcloud" != "springcloud" ?

### ISSUE THREAD

**Issue by zzq1314zll** [apache/incubator-shenyu#3350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="689" alt="image" src="https://user-images.githubusercontent.com/33930711/165445254-ced0a8be-c909-443f-9abd-9eadf7b5f271.png">

### Expected Behavior

can be proxied through the gateway

### Steps To Reproduce

1. I use springcloud + shenyu, the registry uses consul.
This is the configuration of my microservice
```yaml
shenyu:
  register:
    registerType: http
    serverLists: http://localhost:9095
    props:
      username: admin
      password: 123456
  client:
    springCloud:
      props:
        contextPath: ${spring.application.name}
```
2. no "/"
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/33930711/165445023-a2eeef10-3550-4232-9ae2-9d0e747f2f2d.png">
3.  no match
<img width="919" alt="image" src="https://user-images.githubusercontent.com/33930711/165445172-c280308c-1517-4bb2-a89d-4f77384a7e75.png">
4. not the expected result

### Environment

```markdown
ShenYu version(s): master
```

### Anything else?

I think "/" should be automatically filled when registering the api
